version: '2'

services:
  telegrambot:
    build:
      context: .
    container_name: telegram_bot
    restart: always
    ports:
    - 8888:8888
    environment:
      - DB_BILLING=
      - DB_USER=
      - DB_PASS=
      - TG_TOKEN=
      - TG_BOTNAME=